/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import entidade.Autor;
import entidade.Editora;
import entidade.Genero;
import entidade.Livro;
import hibernate.HibernateDao;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author a1294016
 */
public class CadastrarLivros extends javax.swing.JFrame {

    private Livro livro = new Livro();
    private Autor autor = new Autor();
    private Editora editora = new Editora();
    private Genero genero = new Genero();

    /**
     * Creates new form CadastrarLivros
     */
    public CadastrarLivros() throws Exception {
        initComponents();
        List<Editora> aux = new HibernateDao<Editora>().list("nome", editora.getClass(), "", "", "");
        for (int i = 0; i < aux.size(); i++) {
            jCBEditora.addItem(aux.get(i));
        }
        List<Editora> aux1 = new HibernateDao<Editora>().list("nome", autor.getClass(), "", "", "");
        for (int i = 0; i < aux1.size(); i++) {
            jCBAutor.addItem(aux1.get(i));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jLNome = new javax.swing.JLabel();
        jTFQuantidade = new javax.swing.JTextField();
        jLGenero = new javax.swing.JLabel();
        jLQuantidade = new javax.swing.JLabel();
        jCBGenero = new javax.swing.JComboBox();
        jLEditora = new javax.swing.JLabel();
        jLIsbn = new javax.swing.JLabel();
        jTFIsbn = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jBCadastrar = new javax.swing.JButton();
        jLAutor = new javax.swing.JLabel();
        jBAlterar = new javax.swing.JButton();
        jBValidar = new javax.swing.JButton();
        jCBAutor = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jBCadastrarAutor = new javax.swing.JButton();
        jCBEditora = new javax.swing.JComboBox();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1376350938_Books.png"))); // NOI18N
        jLabel1.setText("Cadastrar Livro");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        jLNome.setText("Nome*:");

        jLGenero.setText("Gênero*:");

        jLQuantidade.setText("Quantidade*:");

        jCBGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aventura", "Autoajuda‎", "Biográficos‎", "Científicos", "Contos", "Crônicas‎", "Didáticos", "Romance" }));
        jCBGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGeneroActionPerformed(evt);
            }
        });

        jLEditora.setText("Editora*:");

        jLIsbn.setText("ISBN:");

        jTFIsbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFIsbnActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        jLAutor.setText("Autor*:");

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });

        jBValidar.setText("validar");
        jBValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBValidarActionPerformed(evt);
            }
        });

        jLabel5.setText("Cadastrar Autor:");

        jBCadastrarAutor.setText("Cadastrar Autor");
        jBCadastrarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarAutorActionPerformed(evt);
            }
        });

        jCBEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEditoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLAutor)
                    .addComponent(jLNome)
                    .addComponent(jLEditora)
                    .addComponent(jLIsbn))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jBValidar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCancelar)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTFNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTFIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLGenero))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCBEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLQuantidade))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCBAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCBGenero, 0, 222, Short.MAX_VALUE)
                                    .addComponent(jTFQuantidade)
                                    .addComponent(jBCadastrarAutor))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLQuantidade)
                    .addComponent(jTFQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEditora)
                    .addComponent(jCBEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLGenero)
                        .addComponent(jLIsbn)
                        .addComponent(jTFIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jBCadastrarAutor))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrar)
                    .addComponent(jBCancelar)
                    .addComponent(jBAlterar)
                    .addComponent(jBValidar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBGeneroActionPerformed

    private void jTFIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIsbnActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        if (validar() == false) {
            try {
                persistencia();


                JOptionPane.showMessageDialog(null, " Cadastro realizada com sucesso!!");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, " Não foi possivel cadastrar!!");
            }

        } else {
        }
    }//GEN-LAST:event_jBCadastrarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();

    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBCadastrarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarAutorActionPerformed
        CadastrarAutor cadastrarAutor = new CadastrarAutor();
        cadastrarAutor.setVisible(true);
    }//GEN-LAST:event_jBCadastrarAutorActionPerformed

    private void jBValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBValidarActionPerformed
        validar();
    }//GEN-LAST:event_jBValidarActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
         if (validar() == false) {
            try {
                persistencia();


                JOptionPane.showMessageDialog(null, " Cadastro realizada com sucesso!!");
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, " Não foi possivel cadastrar!!");
            }

        }
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jCBEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEditoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBEditoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarLivros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CadastrarLivros().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(CadastrarLivros.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBCadastrarAutor;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBValidar;
    private javax.swing.JComboBox jCBAutor;
    private javax.swing.JComboBox jCBEditora;
    private javax.swing.JComboBox jCBGenero;
    private javax.swing.JLabel jLAutor;
    private javax.swing.JLabel jLEditora;
    private javax.swing.JLabel jLGenero;
    private javax.swing.JLabel jLIsbn;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLQuantidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JTextField jTFIsbn;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFQuantidade;
    // End of variables declaration//GEN-END:variables

    private boolean validar() {
        StringBuilder stringsBuilder = new StringBuilder();
        if (jTFNome.getText().length() < 3) {
            stringsBuilder.append("Nome é obrigatório\n");
            jLNome.setForeground(Color.red);
        } else {
            jLNome.setForeground(Color.BLACK);
        }
        if (jTFQuantidade.getText().length() <= 0) {
            stringsBuilder.append("Quantidade é obrigatório\n");
            jLQuantidade.setForeground(Color.red);
        } else {
            jLQuantidade.setForeground(Color.BLACK);
        }
        if (jCBEditora.getSelectedItem().toString().trim().length() <= 0) {
            stringsBuilder.append("Editora é obrigatório\n");
            jLEditora.setForeground(Color.red);
        } else {
            jLEditora.setForeground(Color.BLACK);
        }
        if (jCBGenero.getSelectedItem().toString().trim().length() <= 0) {
            stringsBuilder.append("Gênero é obrigatório\n");
            jLGenero.setForeground(Color.red);
        } else {
            jLGenero.setForeground(Color.BLACK);
        }
        if (jCBAutor.getSelectedItem().toString().trim().length() <= 0) {
            stringsBuilder.append("Autor é obrigatório\n");
            jLAutor.setForeground(Color.red);
        } else {
            jLAutor.setForeground(Color.BLACK);
        }
        if (stringsBuilder.length() > 0) {
            JOptionPane.showMessageDialog(null, stringsBuilder.toString());
            return true;
        }
        return false;
    }

    private void persistencia() throws Exception {
        livro.setNomeLivro(jTFNome.getText());
        autor.setNome(jCBAutor.getSelectedItem().toString());
        livro.getAutores().add(autor);
        livro.setQuantidade(Integer.parseInt(jTFQuantidade.getText()));
        editora.setNome(jCBEditora.getSelectedItem().toString());
        livro.getEditoras().add(editora);
        livro.setIsbn(jTFIsbn.getText());
        genero.setGenero(jCBGenero.getSelectedItem().toString());
        livro.setGenero(genero);
        new HibernateDao<Genero>().persist(genero);
        new HibernateDao<Autor>().persist(autor);
        new HibernateDao<Livro>().persist(livro);
    }
}
