/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.DaoUsuario;
import entidade.Usuario;
import hibernate.HibernateDao;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fabio
 */
public class ConsultarUsuario extends javax.swing.JFrame {

    private Usuario usuario = new Usuario();
    List<Usuario> listaUsuario = new ArrayList<>();
    DefaultTableModel tableModel = new DefaultTableModel();

    public ConsultarUsuario() {
        initComponents();

        setTitle("Consultar Cliente");
        tableModel.setColumnIdentifiers(new String[]{
            "ID", "E-mail", "Nome", "Cpf", "Rg", "Telefone"});
        jTAreaDadosConsulta.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGConsulta = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAreaDadosConsulta = new javax.swing.JTable();
        jRBNome = new javax.swing.JRadioButton();
        jRBCpf = new javax.swing.JRadioButton();
        jTFCampoConsulta = new javax.swing.JTextField();
        jBConsultar = new javax.swing.JButton();
        jBFechar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jBAlterar = new javax.swing.JButton();
        jBCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1cadastro.png"))); // NOI18N
        jLabel1.setText("Consultar Usuário");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        jTAreaDadosConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTAreaDadosConsulta.setToolTipText("");
        jScrollPane1.setViewportView(jTAreaDadosConsulta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 598, 264));

        BGConsulta.add(jRBNome);
        jRBNome.setSelected(true);
        jRBNome.setText("Consulta por nome");
        getContentPane().add(jRBNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        BGConsulta.add(jRBCpf);
        jRBCpf.setText("Consulta por cpf");
        getContentPane().add(jRBCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));
        getContentPane().add(jTFCampoConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 410, 25));

        jBConsultar.setText("Consultar");
        jBConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(jBConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 170, -1));

        jBFechar.setText("Cancelar");
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jBFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jBExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 450, -1, -1));

        jBAlterar.setText("Alterar");
        jBAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(jBAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultarActionPerformed

        tableModel.setRowCount(0);
        if (jRBNome.isSelected()) {

            if (jTFCampoConsulta.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Digite  um nome para pesquisar" + jTFCampoConsulta.getText());
            } else {

                try {
                    listaUsuario = new DaoUsuario().retrieveByNome(jTFCampoConsulta.getText());

                    for (Usuario u : listaUsuario) {
                        tableModel.addRow(new Object[]{
                            u.getId(), u.getEmail(), u.getNome(), u.getCpf(), u.getRg(), u.getTelefone()});
                        this.usuario.setId(u.getId());
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Nao foi possivel localizar " + jTFCampoConsulta.getText());
                }
            }
        }else if (jRBCpf.isSelected()) {
             if (jTFCampoConsulta.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Digite  um nome para pesquisar" + jTFCampoConsulta.getText());
            } else {

                try {
                    listaUsuario = new DaoUsuario().retrieveByCpf(jTFCampoConsulta.getText());

                    for (Usuario u : listaUsuario) {
                        tableModel.addRow(new Object[]{
                            u.getId(), u.getEmail(), u.getNome(), u.getCpf(), u.getRg(), u.getTelefone()});
                        this.usuario.setId(u.getId());
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Nao foi possivel localizar " + jTFCampoConsulta.getText());
                }
            }
        }



    }//GEN-LAST:event_jBConsultarActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jBFecharActionPerformed

    private void jBAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarActionPerformed
        int row = jTAreaDadosConsulta.getSelectedRow();
        String sa = tableModel.getValueAt(row, 0).toString();
        int ValorRowColum = Integer.parseInt(sa);
        AlterarUsuario alterarUsuario = new AlterarUsuario();
        try {
            alterarUsuario.preencheTelaCadastro(ValorRowColum);
            alterarUsuario.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBAlterarActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        int row = jTAreaDadosConsulta.getSelectedRow();
        String sa = tableModel.getValueAt(row, 0).toString();
        int ValorRowColum = Integer.parseInt(sa);
        try {
            usuario = new HibernateDao<Usuario>().retrieve(ValorRowColum);
        } catch (Exception ex) {
            Logger.getLogger(ConsultarUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (jTFCampoConsulta.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Selecione um usuario para ser excluidos ");

        } else {
            try {
                if (((int) this.jTAreaDadosConsulta.getValueAt(row, 0)) == usuario.getId()) {
                    new HibernateDao().delete(usuario);
                    tableModel.removeRow(row);
                    JOptionPane.showMessageDialog(null, "Cliente removido com sucesso");
                    jTAreaDadosConsulta.setModel(tableModel);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed
        CadastrarUsuario cadastrarUsuario = new CadastrarUsuario();
        cadastrarUsuario.setVisible(true);
    }//GEN-LAST:event_jBCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarUsuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGConsulta;
    private javax.swing.JButton jBAlterar;
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBConsultar;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBCpf;
    private javax.swing.JRadioButton jRBNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAreaDadosConsulta;
    private javax.swing.JTextField jTFCampoConsulta;
    // End of variables declaration//GEN-END:variables
}
